name: CI

on:
  push:
  pull_request:
  schedule: [cron: "40 1 * * *"]

jobs:
  test:
    name: Rust ${{matrix.rust}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [nightly, beta, stable]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.rust}}
          profile: minimal
          override: true
      - run: cargo build --features bench
        if: matrix.rust == 'nightly'
      - run: cargo test --features bench
        if: matrix.rust == 'nightly'
      - run: cargo bench --features bench
        if: matrix.rust == 'nightly'
      - run: cargo build
  tables:
    name: Verify tables
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Verify regenerated files
        run: ./scripts/unicode.py && rustfmt tables.rs && diff tables.rs src/tables.rs
